"""Create initial schema with tracking_events table

Revision ID: aec0d6d8bb22
Revises: 
Create Date: 2026-02-24 16:47:41.028397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec0d6d8bb22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_order_id'), 'tracking_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_status'), 'tracking_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_events_status'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_order_id'), table_name='tracking_events')
    op.drop_table('tracking_events')
    # ### end Alembic commands ###
